#include "compiler.h"

std::vector<std::shared_ptr<ASTNode>> Compiler::postOrderTraverse(std::shared_ptr<ASTNode> root) {
    if(!root) return {};
    std::vector<std::shared_ptr<ASTNode>> postOrder;
    std::stack<std::shared_ptr<ASTNode>> s1, s2;

    s1.push(root);
    while(!s1.empty()) {
        auto node = s1.top();
        s1.pop();
        s2.push(node);
        for(auto& child : node -> getChildren()) {
            s1.push(child);
        }
    }

    while(!s2.empty()) {
        postOrder.push_back(s2.top());
        s2.pop();
    }

    return postOrder;
}

std::vector<Instruction> Compiler::generateByteCode(const std::vector<std::shared_ptr<ASTNode>>& nodes) {
    std::vector<Instruction> code;
    std::stack<int> storage;
    CompileContext ctx;
    nextTempIndex = 0;
    for(const auto& node : nodes) {
        if(auto num = std::dynamic_pointer_cast<NumberNode>(node)) {
            double val = num -> getValue();
            if(ctx.consts.find(val) == ctx.consts.end()) {
                int target = nextTempIndex++;
                code.push_back({
                    OpCode::LOAD_CONST, -1, -1, target, val
                });
                ctx.consts[val] = target;
            }
            storage.push(ctx.consts[val]);
        } else if(auto var = std::dynamic_pointer_cast<VariableNode>(node)) {
            size_t addr = var -> get_address();
            if(ctx.vars.find(addr) == ctx.vars.end()) {
                int target = nextTempIndex++;
                code.push_back({
                    OpCode::LOAD_VAR, (int)addr, -1, target, 0
                });
                ctx.vars[addr] = target;
            }
            storage.push(ctx.vars[addr]);
        } else if(auto bin = std::dynamic_pointer_cast<BinaryOpNode>(node)) {
            int r = storage.top();
            storage.pop();
            int l = storage.top();
            storage.pop();
            int target = nextTempIndex++;
            code.push_back({
                bin -> getOpCode(), l, r, target, 0
            });
            storage.push(target);
        } else if(auto un = std::dynamic_pointer_cast<UnaryOpNode>(node)) {
            int childIdx = storage.top();
            storage.pop();
            int target = nextTempIndex++;
            code.push_back({
                OpCode::UNARY, childIdx, -1, target, 0
            });
            storage.push(target);
        }
    }
    return code;
}

std::vector<Instruction> Compiler::compile(std::shared_ptr<ASTNode> root) {
    auto postOrder = postOrderTraverse(root);
    return generateByteCode(postOrder);
}

void Compiler::printByteCode(const std::vector<Instruction>& code) const {
    std::cout << "Generated ByteCode" << std::endl;

    for(const auto& inst : code) {
        std::cout << "Op: " << (int)inst.op 
                << " | L: " << inst.left 
                << " | R: " << inst.right 
                << " | Dest: " << inst.dest 
                << " | Val: " << inst.value << std::endl;
    }
}